### ISSUE TITLE
Which echoes package to use

### ISSUE THREAD

**Issue by jernsting** [AlGoulas/bio2art#6]
In the examples the requirements.txt contains the following line:
`echoes==0.1`

When I try to install this version, I encounter this error:

`ERROR: Could not find a version that satisfies the requirement echoes==0.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.1, 0.0.3.2, 0.0.3.3)
ERROR: No matching distribution found for echoes==0.1`

Which echoes package are you using? None of the provided versions of pip seem to work.

**Comment by AlGoulas** [comment]
Hi there - yes you are right. We will update the examples to work with the proper version of echoes. We are on it.

**Comment by AlGoulas** [comment]
Hello there, 

The examples with the echo state network were removed. It was decided not to link the toolbox to any specific type of network, since its very purpose is to be agnostic to any down stream analysis. 

The output of the main functions is a ndarray, so it can be "plugged in" to any type of network (e.g. RNNs as implemented in PyTorch, echo state networks etc).
